/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thoughworks.justiceleague.interfaces.console;

import com.thoughworks.justiceleague.application.ParkingService;
import com.thoughworks.justiceleague.application.impl.ParkingServiceImpl;
import com.thoughworks.justiceleague.domain.parkingBoy.LicensePlateId;
import com.thoughworks.justiceleague.domain.parkingBoy.ParkingBoyId;
import com.thoughworks.justiceleague.domain.parkingBoy.ParkingBoyRepository;
import com.thoughworks.justiceleague.domain.parkingBoy.ParkingLotRepository;
import com.thoughworks.justiceleague.domain.ticket.TicketRepository;
import com.thoughworks.justiceleague.infrastructure.memoryRepository.ParkingBoyRepositoryMemoryImpl;
import com.thoughworks.justiceleague.infrastructure.memoryRepository.ParkingLotRepositoryMemoryImpl;
import com.thoughworks.justiceleague.infrastructure.memoryRepository.TicketRepositoryMemoryImpl;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        ParkingBoyRepository parkingRepo = new ParkingBoyRepositoryMemoryImpl();
        ParkingLotRepository parkingLotRepository = new ParkingLotRepositoryMemoryImpl();
        TicketRepository ticketRepo = new TicketRepositoryMemoryImpl();

        ParkingService parkingService = new ParkingServiceImpl(parkingRepo, parkingLotRepository, ticketRepo);

        parkingService.parking(new ParkingBoyId("parking-boy-001"), new LicensePlateId("川A8888"));
        parkingService.parking(new ParkingBoyId("parking-boy-001"), new LicensePlateId("川A8889"));
        parkingService.parking(new ParkingBoyId("parking-boy-001"), new LicensePlateId("川A8810"));
        parkingService.parking(new ParkingBoyId("parking-boy-001"), new LicensePlateId("川A8811"));

        System.out.println(parkingRepo.find(new ParkingBoyId("parking-boy-001")));
    }
}
