spring:
  application:
    name: justice-league-parking-service
  datasource:
    url: jdbc:h2:mem:parking_service;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS parking_service
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        event:
          merge:
            entity_copy_observer: allow

  flyway:
    locations: classpath:/db/migration
    check-location: false

  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true

parking-lot-service:
  url: http://localhost:6565

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server:8080/eureka/